//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BurgerPlusEntities1 : DbContext
    {
        private static BurgerPlusEntities1 _context;
        public static BurgerPlusEntities1 GetContext()
        {
            if (_context == null)
                _context = new BurgerPlusEntities1();
            return _context;
        }
        public BurgerPlusEntities1()
            : base("name=BurgerPlusEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Edinica_Izmerenia> Edinica_Izmerenia { get; set; }
        public virtual DbSet<Price_Materials> Price_Materials { get; set; }
        public virtual DbSet<Price_Product> Price_Product { get; set; }
        public virtual DbSet<Proizvod_Materials> Proizvod_Materials { get; set; }
        public virtual DbSet<Proizvod_Product> Proizvod_Product { get; set; }
        public virtual DbSet<Rasschet_Stoimosti_Product> Rasschet_Stoimosti_Product { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Specifikacia_Materials> Specifikacia_Materials { get; set; }
        public virtual DbSet<Specifikacia_Product> Specifikacia_Product { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Zakaz_Pokypatel> Zakaz_Pokypatel { get; set; }
        public virtual DbSet<Zakazchiki> Zakazchiki { get; set; }
    }
}
