//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price_Materials
    {
        public int Id_Price_Mat { get; set; }
        public int Id_ProizvMat { get; set; }
        public decimal Price { get; set; }
    
        public virtual Proizvod_Materials Proizvod_Materials { get; set; }
    }
}
