//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price_Product
    {
        public int Id_Price_Product { get; set; }
        public int Id_ProizProduct { get; set; }
        public decimal Cena { get; set; }
    
        public virtual Proizvod_Product Proizvod_Product { get; set; }
    }
}
