//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvod_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvod_Product()
        {
            this.Price_Product = new HashSet<Price_Product>();
            this.Rasschet_Stoimosti_Product = new HashSet<Rasschet_Stoimosti_Product>();
            this.Specifikacia_Product = new HashSet<Specifikacia_Product>();
        }
    
        public int Id_ProizProduct { get; set; }
        public string Name { get; set; }
        public string Kode { get; set; }
        public int Kolichestvo { get; set; }
        public int Id_Edinic { get; set; }
    
        public virtual Edinica_Izmerenia Edinica_Izmerenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price_Product> Price_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rasschet_Stoimosti_Product> Rasschet_Stoimosti_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specifikacia_Product> Specifikacia_Product { get; set; }
    }
}
