//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvod_Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvod_Materials()
        {
            this.Price_Materials = new HashSet<Price_Materials>();
            this.Rasschet_Stoimosti_Product = new HashSet<Rasschet_Stoimosti_Product>();
            this.Specifikacia_Materials = new HashSet<Specifikacia_Materials>();
        }
    
        public int Id_ProizvMat { get; set; }
        public string Name { get; set; }
        public string Kode { get; set; }
        public double Kolichestvo { get; set; }
        public int Id_Edinic { get; set; }
    
        public virtual Edinica_Izmerenia Edinica_Izmerenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price_Materials> Price_Materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rasschet_Stoimosti_Product> Rasschet_Stoimosti_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specifikacia_Materials> Specifikacia_Materials { get; set; }
    }
}
