//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specifikacia_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specifikacia_Product()
        {
            this.Specifikacia_Materials = new HashSet<Specifikacia_Materials>();
        }
    
        public int Id_Specifikacia { get; set; }
        public int Id_ProizProduct { get; set; }
        public decimal Cena { get; set; }
    
        public virtual Proizvod_Product Proizvod_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specifikacia_Materials> Specifikacia_Materials { get; set; }
    }
}
