//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specifikacia_Materials
    {
        public int Id_SpecMat { get; set; }
        public int Id_Specifikacia { get; set; }
        public int Id_ProizvMat { get; set; }
        public int Id_Edinic { get; set; }
        public double Kolichestvo { get; set; }
    
        public virtual Edinica_Izmerenia Edinica_Izmerenia { get; set; }
        public virtual Proizvod_Materials Proizvod_Materials { get; set; }
        public virtual Specifikacia_Product Specifikacia_Product { get; set; }
    }
}
