//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Zakazchiki = new HashSet<Zakazchiki>();
        }
    
        public int Id_Users { get; set; }
        public int Id_Role { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Patronymic { get; set; }
        public int Status_Id { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakazchiki> Zakazchiki { get; set; }
    }
}
