//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazchiki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakazchiki()
        {
            this.Zakaz_Pokypatel = new HashSet<Zakaz_Pokypatel>();
        }
    
        public int Id_Zakazchik { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Inn { get; set; }
        public string Gorod { get; set; }
        public string Street { get; set; }
        public string Phone { get; set; }
        public string Salesman { get; set; }
        public double Buyer { get; set; }
        public int Id_Users { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz_Pokypatel> Zakaz_Pokypatel { get; set; }
    }
}
