//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz_Pokypatel
    {
        public int Id_Zakaz { get; set; }
        public int Kolichestvo { get; set; }
        public int Id_Edinic { get; set; }
        public decimal Cena { get; set; }
        public decimal Summa { get; set; }
        public int Id_Zakazchika { get; set; }
    
        public virtual Edinica_Izmerenia Edinica_Izmerenia { get; set; }
        public virtual Zakazchiki Zakazchiki { get; set; }
    }
}
